### ISSUE TITLE
ResultCode.php s C0_OK hazi vyjimku ale nemel by... 

### ISSUE THREAD

**Issue by petasan** [slevomat/csob-gateway#12]
zlobi if (!self::isValidValue($value)) {

pri hodnote 
  const C0_OK = 0;
to vraci vyjimku.

**Comment by janlanger** [comment]
Chtělo by to ukázku kódu který vyhazuje vyjímku nebo (ideálně) failující test.

**Comment by petasan** [comment]
Testovani jsem zjsitil ze test brana CSOB vraci kod 0, ale je to asi string ale vy mate v enmumu strict type na 0 na cislo tim to asi je... 
isValidValue() {... return in_array($value, self::getAvailableValues(), true); }

kdyz jsem dal 
isValidValue() {... return in_array($value, self::getAvailableValues()); }

Tak mi to proslo... 

diky. 

![invalidenumvalueexception](https://cloud.githubusercontent.com/assets/12389482/14663315/eedec9c4-06bf-11e6-9bb2-aa2cd5663933.png)

**Comment by petasan** [comment]
Stejny problem je v pripade equalsValue(); Vypada to ze brana CSOB vraci misto cisel stringy .... diky.

**Comment by petasan** [comment]
v oficial prikade jsem nasel.... 
`class PaymentStatus {
	static $requested = '1';
	static $pending = '2';
	static $canceled = '3';
	static $approved = '4';
	static $reversed = '5';
	static $declined = '6';
	static $toClearing = '7';
	static $cleared = '8';
	static $refundRequested = '9';
	static $refunded = '10';
}`

Praciji s Csob branou v1.5.... cislelne kody sedi jen se to jinak jmenuje...

**Comment by pepakriz** [comment]
Podle [dokumentace](https://github.com/csob/paymentgateway/wiki/eAPI-1.5#n%C3%A1vratov%C3%A9-hodnoty-) má být `resultCode` a `paymentStatus` number. Což v json datech opravdu je. Váš problém pravděpodobně nastává jen u volání `createReceivePaymentRequest`, kde předáváte data, která vám brána poslala přes GET (případně POST) a zde jsou všechny datové typy typu string. Takže ukázku z readme je třeba mírně upravit na něco jako:

```php
$paymentResponse = $requestFactory->createReceivePaymentRequest()->send($apiClient, [
    'payId' => $_POST['payId'],
    'resultCode' => (int) $_POST['resultCode'],
    'paymentStatus' => (int) $_POST['paymentStatus'],
]);
```

**Comment by petasan** [comment]
Omluva a diky za rychlou reakci...

**Comment by pepakriz** [comment]
V pořádku. Nepřesnosti v readme upravíme.

**Comment by janlanger** [comment]
Díky za report. Přetypování teď probíhá automaticky.
