### ISSUE TITLE
Chyba v příkladu v Usage

### ISSUE THREAD

**Issue by arxeiss** [slevomat/csob-gateway#25]
Při vytváření ApiClient není v příkladu uvedeno, že třetí parametr má být ještě URL na bránu. A pak ani v jakém formátu.

Nevím proč je to navíc nepovinný parametr, když se stejně nikde v kódu nedoplňuje, a pak PHP ani nevyhodí chybu při jeho nevyplnění. Když verze kódu je navíc pro danou verzi API, nebylo by lepší do konstruktoru ApiClient předat parametr $isProduction a podle toho doplnit URL adresu ve třídě ApiClient automaticky? Takové řešení má třeba GoPay u své implementace.

**Comment by janlanger** [comment]
Díky za report, signaturu konstruktoru a dokumentaci jsem opravil.

Nastavování prostředí místo URL zvážíme pro příští verze.
