### ISSUE TITLE
Povinný parametr Language

### ISSUE THREAD

**Issue by arxeiss** [slevomat/csob-gateway#26]
Cituji z dokumentace

> Preferovaná jazyková mutace, která se zobrazí zákazníkovi na platební bráně. Od verze 1.6 povinný parametr. Povolené hodnoty: CZ, EN, DE, FR, HU, IT, JP, PL, PT, RO, RU, SK, ES, TR, VN. Stejnou jazykovou sadu lze použít i v eAPI v1 a v1.5

U vás je language nepovinný parametr a response poté vrací hlášku v 

> ["resultMessage":"SlevomatCsobGateway\Call\PaymentResponse":private]=>string(26) "Missing parameter language"

**Comment by arxeiss** [comment]
Moje chyba, špatně jsem pochopil kód.

Vy totiž máte $language jako povinný parametr, ale před ním jsou 2 nepovinné. Toto pokud vím ani v PHP7 se nezměnilo, a všechny nepovinné by měly být vždy napravo od povinných.

**Comment by janlanger** [comment]
Parametry jsou seřazené tak jak jsou uvedené v dokumentaci ČSOB brány a to je pořadí kterého se chceme držet.

**Comment by arxeiss** [comment]
To chápu, pak by ale parametry merchantData a customeId neměly být nepovinné, i když pro API nepovinné jsou. Stejně se musejí zadat aby se mohlo zadat $language

**Comment by ondrejmirtes** [comment]
PHP < 7.1 neumí rozlišit mezi nullability a optionality parametru metody. Oboje se dělá pomocí `= null`. V PHP 7.1 se nullability dělá pomocí `?string $foo` a optionality pomocí nastavení defaultní hodnoty `string $foo 'foo'` (či null).

V našem případě jsou ty argumenty, které jsou následovány povinnými, pouze nullable (a povinné). Na jejich pořadí je vše v pořádku.
