### ISSUE TITLE
Rozšíření EET - payment/init apod

### ISSUE THREAD

**Issue by arxeiss** [slevomat/csob-gateway#29]
API od ČSOB nyní podporuje EET, které ale předává více dat v metodě init a dalších.
Máte v plánu tuto funkcionalitu přidat také do vaší knihovny? Hledal jsem, ale nemohl jsem nic najít.

Děkuji

**Comment by janlanger** [comment]
@arxeiss Pokud někdo připraví PR, tak samozřejmě není problém. 
Ve Slevomatu jsme museli řešit EET už s první vlnou a máme ho integrované přímo do našeho systému (s pomocí slevomat/eet-client), takže podpora přes pl. bránu pro nás nemá prioritu...
