### ISSUE TITLE
Transakce bila zamítnuta

### ISSUE THREAD

**Issue by MakingCG** [slevomat/csob-gateway#35]
Ahojte,

Mam mensi problem s touto kniznicou a po hlbsej analyze som nenasiel riesenie a uz vobec neviem kde este hladat tak sa na Vas obraciam. Po zalozeni platby ma presmeruje na danu stranku banky no ihned sa zobrazi hlaska 'Transakce bila zamítnuta'. V odpovedi som dostal 'paymentStatus' 6 (platba zamietnuta) s 'resultMessage' Ok, cize to mi vela nepovie kde som mohol urobit chybu. Ak niekto pozna riesenie, budem vdacny, dakujem.

Zalozenie platby 1
<img width="939" alt="screenshot 2018-10-01 at 16 47 14" src="https://user-images.githubusercontent.com/17012967/46296456-b4937c00-c59a-11e8-8889-43fa148ef10d.png">

Zalozenie platby 2
<img width="911" alt="screenshot 2018-10-01 at 16 47 27" src="https://user-images.githubusercontent.com/17012967/46296607-06d49d00-c59b-11e8-8f94-115b10b612b0.png">

Presmerovanie na platobnu branu
<img width="736" alt="screenshot 2018-10-01 at 16 45 19" src="https://user-images.githubusercontent.com/17012967/46296498-c9700f80-c59a-11e8-9b08-beb3669c3b61.png">

Odpoved po presmerovani na stranku
<img width="376" alt="screenshot 2018-10-01 at 16 44 57" src="https://user-images.githubusercontent.com/17012967/46296521-d4c33b00-c59a-11e8-97e6-512139bbf145.png">

Diki moc.

**Comment by janlanger** [comment]
S tím vám asi poradí spíše support brány https://github.com/csob/paymentgateway/issues

**Comment by MakingCG** [comment]
Dakujem,

problem bol v tom ze zakladam platbu v mene EUR, ktora ale v testovacom rezime nie je povolena.
