### ISSUE TITLE
PHP 8 - composer zavislosti

### ISSUE THREAD

**Issue by Lumeriol** [slevomat/csob-gateway#46]
Při pokusu stáhnout přes Composer tento balíček je problém se závislostí na consistence/consistence 2.0.1, který nepodporuje PHP 8. Bylo by možné tuto závislost nahradit forknutým balíčkem  slevomat/consistence-consistence, kde je podpora již zahrnuta?

**Comment by janlanger** [comment]
Zatím jsme se nerozhodli co s consistence uděláme. slevomat/consistence-consistence je fork, který používáme interně, prozatím můžete podporu PHP 8 vyřešit přidáním do repositories v composer.json (https://getcomposer.org/doc/04-schema.md#repositories)

**Comment by janlanger** [comment]
Ve verzi 5.2.0 byl consistence nahrazeno forkem. https://github.com/slevomat/csob-gateway/releases/tag/5.2.0
