### ISSUE TITLE
Refund request vyhodí InvalidSignatureException

### ISSUE THREAD

**Issue by MMirekk** [slevomat/csob-gateway#60]
Dobrý den,
při testování mi vše funguje jak má, ale při pokusu refundovat platbu mi u response vyhodí Exception na řádku #305 /src/api/Driver/ApiClient.php InvalidSignatureException
Přitom když si zapnu logování, tak odpověď mi z ČSOB brány normálně přijde.
Používám metodu createRefundPayment z RequestFactory.php
U jiných metod se toto neděje. Díky

**Comment by janlanger** [comment]
Dobrý den, víme k tom, bohuzel netuším kde je problém. Posílali jsme to na prověření na support platební brány, zatím čekáme na reakci

**Comment by MMirekk** [comment]
Díky moc za pomoc
