### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by adam-janca** [slevomat/csob-gateway#62]
Dobrý den,

v první řadě děkuji za vývoj balíčku. 

V druhé řadě jsem se chtěl zeptat, zdali jste nezvažovali podporu i pro PHP 8.0. Na našem eshopovem systému bychom to využili.

Díky za info.

**Comment by janlanger** [comment]
Dobrý den, s PHP 8.0 je kompatibilní verze 5. 
PHP 8.0 [končí za necelý měsíc aktivní podpora](https://www.php.net/supported-versions.php). Nové verze ČSOB api vycházejí po několika letech a vzhledem k tomu, že přechod na 8.1 nám umožnil zbavit se jediné závislosti, rozhodli jsme se vyžadovat v aktuální verzi PHP 8.1.
